/* Base code structure credit http://html-tuts.com/display-random-content-javascript/ */
randomNumber = Math.floor(Math.random()*4+1);

document.addEventListener('DOMContentLoaded', (event) => {
    if (randomNumber == 1) {
		document.getElementById("reviewOne").innerHTML = "<div class='feature-testimonial'><span class='badge badge-success'>Feature Review</span><br/><i>I LOVE And Bible. It is the best Bible app out there. I have Logos and Olive Tree as well for a few copyright resources, but And Bible is my daily Bible.</i> <br/> <b>Jared Hood, OT Lecturer, Academic Dean: Presbyterian Theological College <br/> Executive Editor: Reformed Theological Review</b> <br/> </div><hr/>";
		document.getElementById("reviewTwo").innerHTML = "<i>This app has come a long way. It is now my favorite study tool on Android platforms. Excellent work! The September 2021 update is great; this project continues to impress me!</i> <br/> <b>-J.B., AndBible user</b> <br/> <span class='fa fa-star checked'></span><span class='fa fa-star checked'></span><span class='fa fa-star checked'></span><span class='fa fa-star checked'></span><span class='fa fa-star checked'></span> <small>(Google Play)</small> <hr/>";
		document.getElementById("reviewThree").innerHTML = "<i>This is an excellent, powerful, and free resource for studying the word of God. I love how the interface design is clean and simple, yet the wealth of information accessible to you is so extensive. I use it as an invaluable reference tool for commentaries, Greek translation, and Spanish and German translation when on gospel trips to South America and Germany. Though this app isn't perfect, it accomplishes its various functions very well. Thank you!</i> <br/> <b>-G.A., AndBible user</b> <br/> <span class='fa fa-star checked'></span><span class='fa fa-star checked'></span><span class='fa fa-star checked'></span><span class='fa fa-star checked'></span><span class='fa fa-star checked'></span> <small>(Google Play)</small><hr/>";
		document.getElementById("reviewFour").innerHTML = "<i>The And Bible app is a treasure trove of resources for Bible study.  This is the one app I use daily, whether it be for daily reading, family devotion, personal or group Bible study, or sermon prep.  This app has surely been a blessing and has helped me in my walk with God.</i> <br/> <b>-C.R., Pastor</b> <br/> <span class='fa fa-star checked'></span><span class='fa fa-star checked'></span><span class='fa fa-star checked'></span><span class='fa fa-star checked'></span><span class='fa fa-star checked'></span> <small>(Google Play)</small>";
	}
	if (randomNumber == 2) {
		document.getElementById("reviewOne").innerHTML = "<div class='feature-testimonial'><span class='badge badge-success'>Feature Review</span><br/><i>I LOVE And Bible. It is the best Bible app out there. I have Logos and Olive Tree as well for a few copyright resources, but And Bible is my daily Bible.</i> <br/> <b>Jared Hood, OT Lecturer, Academic Dean: Presbyterian Theological College <br/> Executive Editor: Reformed Theological Review</b> <br/></div> <hr/>";
		document.getElementById("reviewTwo").innerHTML = "<i>This is a fantastic resource. I am a better Christian and a better steward of God's word for having ready access to it.</i> <br/> <b>-J.L., AndBible user</b> <br/> <span class='fa fa-star checked'></span><span class='fa fa-star checked'></span><span class='fa fa-star checked'></span><span class='fa fa-star checked'></span><span class='fa fa-star checked'></span> <small>(Google Play)</small><hr/>";
		document.getElementById("reviewThree").innerHTML = "<i>One of the most underrated Apps in the store. I wish the ratings system went to 10; this is the best app for Bible students. My hat is off to the developers. Some of the best translations and commentaries that currently exist are here... for free. How are all the reviews not 5 stars?</i> <br/> <b>-J.F., AndBible user</b> <br/> <span class='fa fa-star checked'></span><span class='fa fa-star checked'></span><span class='fa fa-star checked'></span><span class='fa fa-star checked'></span><span class='fa fa-star checked'></span> <small>(Google Play)</small><hr/>";
		document.getElementById("reviewFour").innerHTML = "<i>If you are an Android user and don't have And Bible app, you're wasting your time on the others. By far the Best Free Bible app out there.</i> <br/> <b>-D.F., AndBible user</b> <br/> <span class='fa fa-star checked'></span><span class='fa fa-star checked'></span><span class='fa fa-star checked'></span><span class='fa fa-star checked'></span><span class='fa fa-star checked'></span> <small>(Google Play)</small>";
	}
	if (randomNumber == 3) {
		document.getElementById("reviewOne").innerHTML = "<div class='feature-testimonial'><span class='badge badge-success'>Feature Review</span><br/><i>I LOVE And Bible. It is the best Bible app out there. I have Logos and Olive Tree as well for a few copyright resources, but And Bible is my daily Bible.</i> <br/> <b>Jared Hood, OT Lecturer, Academic Dean: Presbyterian Theological College <br/> Executive Editor: Reformed Theological Review</b> <br/> </div><hr/>";
		document.getElementById("reviewTwo").innerHTML = "<i>The And Bible app is a treasure trove of resources for Bible study.  This is the one app I use daily, whether it be for daily reading, family devotion, personal or group Bible study, or sermon prep.  This app has surely been a blessing and has helped me in my walk with God.</i> <br/> <b>-C.R., Pastor</b><br/> <span class='fa fa-star checked'></span><span class='fa fa-star checked'></span><span class='fa fa-star checked'></span><span class='fa fa-star checked'></span><span class='fa fa-star checked'></span> <small>(Google Play)</small><hr/>";
		document.getElementById("reviewThree").innerHTML = "<i>This is a fantastic resource. I am a better Christian and a better steward of God's word for having ready access to it.</i> <br/> <b>-J.L., AndBible user</b> <br/> <span class='fa fa-star checked'></span><span class='fa fa-star checked'></span><span class='fa fa-star checked'></span><span class='fa fa-star checked'></span><span class='fa fa-star checked'></span> <small>(Google Play)</small><hr/>";
		document.getElementById("reviewFour").innerHTML = "<i>One of the most underrated Apps in the store. I wish the ratings system went to 10; this is the best app for Bible students. My hat is off to the developers. Some of the best translations and commentaries that currently exist are here ... for free. How are all the reviews not 5 stars?</i> <br/> <b>-J.F., AndBible user</b> <br/> <span class='fa fa-star checked'></span><span class='fa fa-star checked'></span><span class='fa fa-star checked'></span><span class='fa fa-star checked'></span><span class='fa fa-star checked'></span> <small>(Google Play)</small>";
	}
	if (randomNumber == 4) {
		document.getElementById("reviewOne").innerHTML = "<div class='feature-testimonial'><span class='badge badge-success'>Feature Review</span><br/><i>I LOVE And Bible. It is the best Bible app out there. I have Logos and Olive Tree as well for a few copyright resources, but And Bible is my daily Bible.</i> <br/> <b>Jared Hood, OT Lecturer, Academic Dean: Presbyterian Theological College <br/> Executive Editor: Reformed Theological Review</b><br/> </div><hr/>";
		document.getElementById("reviewTwo").innerHTML = "<i>It's nice that they only use 'legal' Bibles. A very good app; it's fast and easy to use. In no other application had I found the Reina Valera 1909 Bible with italic letters, as in the printed one and with Strong's numbers. It has been very useful, thank you. Blessings!</i> <br/> <b>-H.W., AndBible user</b><br/> <span class='fa fa-star checked'></span><span class='fa fa-star checked'></span><span class='fa fa-star checked'></span><span class='fa fa-star checked'></span><span class='fa fa-star checked'></span> <small>(Google Play)</small><hr/>";
		document.getElementById("reviewThree").innerHTML = "<i>The 'Bible Study App' (And Bible) for Android is so good that when I'm studying the Bible and I use desktop software I often find myself going back to my Android device because of ease of use and the many features that it has. It helps me to easily organize my thoughts with labels and study pads. The best Bible app for mobile and tablets, bar none!</i> <br/> <b>-T.B., AndBible user</b> <br/> <span class='fa fa-star checked'></span><span class='fa fa-star checked'></span><span class='fa fa-star checked'></span><span class='fa fa-star checked'></span><span class='fa fa-star checked'></span> <small>(Google Play)</small><hr/>";
		document.getElementById("reviewFour").innerHTML = "<i>Excellent application, the best. You can see different versions, dictionaries in Greek and Hebrew (to English) and biblical commentaries ... it's like having the study library in your pocket. Thanks! <br/> <b>-A.B., AndBible user</b> <br/> <span class='fa fa-star checked'></span><span class='fa fa-star checked'></span><span class='fa fa-star checked'></span><span class='fa fa-star checked'></span><span class='fa fa-star checked'></span> <small>(Google Play)</small>";
	}
});